### ISSUE TITLE
Unsucessful building linphone-desktop RPM package Fedora 34

### ISSUE THREAD

**Issue by leukimi** [BelledonneCommunications/linphone-desktop#512]
# Building linphone-desktop RPM package on Fedora 34 (standard out of the box installation)
It is very difficult to manage to build linphone-desktop RPM package from the instructions on how to do it. Would appreciate precise building instructions that actually create a working build. Compilation usually fails on cmake error message 2 which doesn't really tell what is wrong. There are so many building parts that it is very difficult to understand what went wrong during the cmake compilation and be able to correct it.

Depending on which NDK (tried 17, 18, 20, 21, 22) version that is used, and it seems that one also has to install Android Studio although there is no instruction on it, where Android Studio also can install NDK, issues with permissions to Android Studio to install plugins, it becomes rocket science to make any tested branch of linphone-desktop to compile. Tried the linphone-desktop branches master, 4.1, 4.2 and 4.3 without success. They all fail at different places and cmake says "error 2" at some stage, probably in the building of Linphone-SDK and building of liblinphone.

Maybe it would be easier if there was a complete tutorial on exactly which versions of all packages that are needed to allow successful compilation.

Maybe it would be easier if the Linphone-SDK was not needed to be compiled locally, if it is difficult to compile it. Maybe liblinphone could be sourced in another way than building Linphone-SDK from scratch.

Please, install a clean Fedora 34 and try to follow the project's own building instructions on how it is to be compiled with cmake and see what errors you will encounter and please write a detailed "How you compile linphone-desktop on Fedora 34" to ease the headache on how this software is able to compile. That would be very helpful.

The project could compile RPM and DEB packages alongside the AppImage to be used. Ubuntu Budgie 21.04 seems to have Linphone in the gnome-software center ready for install. Maybe something similar could be possible for Fedora 34. In any case it would feel nice to be able to compile the software per your instruction successfully.

Thank you in advance to create a precise instruction on how to proceed, exactly which branches to clone for each piece of software that is needed, all the necessary steps from scratch on for instance a clean install Fedora 34 and a clean install Ubuntu 20.04. That would help a lot.

**Comment by julonexus** [comment]
Hi
Linphone Desktop doesn't support Android so I don't know what you're talking about.
If you want more help, you have to ask on mailing list. This is not the place for asking help.
Regards

**Comment by leukimi** [comment]
# Just for clarification
The idea is to successfully compile `linphone-desktop` on any kind of linux. Fedora 34 is the chosen platform.

Try to install a fresh Fedora 34.

Try to follow the [building instructions in this very repository](https://github.com/BelledonneCommunications/linphone-desktop#readme).

See what building errors you get.

Maybe you will notice that it is impossible to compile `linphone-desktop` with the instructions given.

You might see that the code starts to compile `linphone-sdk @ 6386066`, which for some reason needs an NDK to compile, which for some reasons requires Android Studio, extra scripts etcetera ...

Agree that it is weird that to compile `linphone-desktop` ,  `linphone-sdk @ 6386066` is also built automatically but fails, where `cmake` returns an `Error 2` after a while and that is the end. That is unfortunately what happens when you follow the [building instructions in this very repository](https://github.com/BelledonneCommunications/linphone-desktop#readme).

If you have a way to compile `linphone-desktop` other than the [building instructions in this very repository](https://github.com/BelledonneCommunications/linphone-desktop#readme) you are most welcome to share those building steps that are needed.

Unfortunately the mailing lists is probably not the easiest way to get this piece of software to compile on any kind of linux. People will come here, to the source code to find out how you are supposed to compile it. Just for comparison: your friends at `signal-desktop` have building instructions that compile flawlessly, if you want to compare. Any help is appreciated, because many will benefit.

Please make a guide on how to compile this software on Fedora 34 in your preferred way. Following the [building instructions in this very repository](https://github.com/BelledonneCommunications/linphone-desktop#readme) does not result in a successful `linphone-desktop` executable or RPM package.

I hope it helps to explain that the instructions are not easy to follow and they don't produce a working `linphone-desktop`, which is sad.

**Comment by julonexus** [comment]
The issue tracker have not a goal to get complains.
We'll not use our free time on individual issues with post that keep repeating [building instructions in this very repository](https://github.com/BelledonneCommunications/linphone-desktop#readme) without posting any logs.

Following exactly instructions is done on all platforms. So maybe you are not following exactly them.
I'm on Fedora 33 and I don't have NDK. Why it is not the same on Fedora 34? I don't know and your post doesn't help.

**Comment by leukimi** [comment]
I will try to describe my attempts and I would appreciate your help to be able to compile an RPM for Fedora 34.

I tried to narrow down my problem by first trying different gcc compilers (v11, v9.3), then I tried different versions of Qt (5.15, 5.12.5). What remains is to try a specific (complete) source code version of `linphone-desktop` that is the base of the v4.2.5 which is on the website as AppImage, or a version 4.3.x that is known to compile successfully on lets say Fedora 33.

Tried to build `linphone-desktop`with Fedora 34 official `gcc11.1.1` and also installed `gcc9.3.0` with the help of `gcc-builder` ([link to gcc-builder](https://bobsteagall.com/2017/12/30/gcc-builder/)). `gcc9.3.0` seems to sometimes be a better choice for compiling a bit older code, and it is the gcc used by Ubuntu 20.04LTS, so I tried it first.

Compared to Fedora 34, Fedora 33 seems to have `gcc10.x`, which I haven't tried yet. Maybe `gcc10` does a better job than `gcc9.3` or `gcc11`.

Qt v5.12.5 seems to be compatible at least with `gcc7` and compiles well with `gcc9.3.0`.
`gcc11` is sometimes causing some compilation errors, which `gcc9.3.0` doesn't.
`gcc11` does not manage to build Qt v5.12.5 on my machine, but `gcc9.3.0` succeeds.

The only issue with `gcc9.3.0` is that one has to re-link the libraries from v6.0.**28** to v6.0.**29**, which can be copied from `/usr/lib64/libstdc++.so.6.0.29`:

```sh
ln -sf libstdc++.so.6.0.29 libstdc++.so 
ln -sf libstdc++.so.6.0.29 libstdc++.so.6
```

## First attempt
Tried to build `linphone-desktop` with Fedora 34 official Qt v5.15.x (added package `qt5-qtbase-devel` to get the required `cmake` files). The Qt v15.x files are on Fedora 34 found here:
```sh
Qt5_DIR="/usr/lib64/cmake/Qt5"
PATH="/usr/lib64/qt5/bin:$PATH"
```
## Second attempt
Tried and suceeded to build Qt v5.12.5 with `gcc9.3.0` from source and install it to `~/Qt/5.12.5`.
Adjusted all the variables:
```sh
Qt5_DIR="~/Qt/5.12.5/lib/cmake"
PATH="~/Qt/5.12.5/bin/:$PATH"
```
## Third attempt

1. Tried to compile git branch `master`.
2. Tried to compile git branch `tags/4.2.5`
3. Tried to compile git branch `origin/release/4.2`
4. Tried to compile git branch `origin/release/4.3`

```sh
mkdir -p linphone-desktop/build
cd linphone-desktop/build
cmake .. -DCMAKE_BUILD_PARALLEL_LEVEL=10 -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build . --target install --parallel 10 --config RelWithDebInfo
```

All my attempts seem to fail in the same spot, regardless of gcc, regardless of Qt:

```sh
[ 82%] Performing post-installation for 'EP_openldap'
[ 82%] Completed 'EP_openldap'
[ 83%] Built target EP_openldap
gmake[6]: *** [Makefile:91: all] Error 2
gmake[5]: *** [CMakeFiles/sdk.dir/build.make:88: sdk-prefix/src/sdk-stamp/sdk-build] Error 2
gmake[4]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sdk.dir/all] Error 2
gmake[3]: *** [Makefile:91: all] Error 2
gmake[2]: *** [CMakeFiles/sdk.dir/build.make:88: WORK/stamp/sdk-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/sdk.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

I tried to figure out what the error means and why it happens.
`sdk-prefix/src/sdk-stamp/sdk-build` is not created. 

If I run `../configure` in the `openldap/build` folder, it says something about:

`configure: error: BDB/HDB: BerkeleyDB not available`

Maybe the error has nothing to do with `openldap` (`EP_openldap` seems to be built). Maybe the error is connected to the next step in the building process.

```sh
cd linphone-desktop/linphone-sdk/external/openldap/build
../configure
# Output below:
Configuring OpenLDAP 2.4.X-Engineering ...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking configure arguments... done
checking for cc... cc
checking for ar... ar
checking for style of include used by make... GNU
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking dependency style of cc... none
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognise dependent libraries... pass_all
checking how to run the C preprocessor... cc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 32768
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ranlib... ranlib
checking for strip... strip
checking if cc static flag  works... yes
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
configure: creating libtool
checking how to run the C preprocessor... cc -E
checking whether we are using MS Visual C++... no
checking for be_app in -lbe... no
checking whether we are using the GNU C compiler... (cached) yes
checking whether cc accepts -g... (cached) yes
checking for cc option to accept ISO C89... (cached) none needed
checking dependency style of cc... (cached) none
checking for cc depend flag... -M
checking for afopen in -ls... no
checking for EBCDIC... no
checking for ANSI C header files... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for sys/wait.h that is POSIX.1 compatible... yes
checking whether termios.h defines TIOCGWINSZ... no
checking whether sys/ioctl.h defines TIOCGWINSZ... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking arpa/nameser.h usability... yes
checking arpa/nameser.h presence... yes
checking for arpa/nameser.h... yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking bits/types.h usability... yes
checking bits/types.h presence... yes
checking for bits/types.h... yes
checking conio.h usability... no
checking conio.h presence... no
checking for conio.h... no
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
checking direct.h usability... no
checking direct.h presence... no
checking for direct.h... no
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking filio.h usability... no
checking filio.h presence... no
checking for filio.h... no
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for memory.h... (cached) yes
checking psap.h usability... no
checking psap.h presence... no
checking for psap.h... no
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking process.h usability... no
checking process.h presence... no
checking for process.h... no
checking sgtty.h usability... yes
checking sgtty.h presence... yes
checking for sgtty.h... yes
checking shadow.h usability... yes
checking shadow.h presence... yes
checking for shadow.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking sys/filio.h usability... no
checking sys/filio.h presence... no
checking for sys/filio.h... no
checking sys/fstyp.h usability... no
checking sys/fstyp.h presence... no
checking for sys/fstyp.h... no
checking sys/errno.h usability... yes
checking sys/errno.h presence... yes
checking for sys/errno.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/privgrp.h usability... no
checking sys/privgrp.h presence... no
checking for sys/privgrp.h... no
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking sys/syslog.h usability... yes
checking sys/syslog.h presence... yes
checking for sys/syslog.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/types.h... (cached) yes
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/vmount.h usability... no
checking sys/vmount.h presence... no
checking for sys/vmount.h... no
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking utime.h usability... yes
checking utime.h presence... yes
checking for utime.h... yes
checking for resolv.h... yes
checking for netinet/tcp.h... yes
checking for sys/ucred.h... no
checking for sigaction... yes
checking for sigset... yes
checking for socket... yes
checking for select... yes
checking for sys/select.h... (cached) yes
checking for sys/socket.h... (cached) yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking for poll... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking sys/poll.h usability... yes
checking sys/poll.h presence... yes
checking for sys/poll.h... yes
checking sys/epoll.h usability... yes
checking sys/epoll.h presence... yes
checking for sys/epoll.h... yes
checking for epoll system call... yes
checking sys/devpoll.h usability... no
checking sys/devpoll.h presence... no
checking for sys/devpoll.h... no
checking declaration of sys_errlist... no
checking existence of sys_errlist... no
checking for strerror... yes
checking for strerror_r... yes
checking non-posix strerror_r... no
checking for regex.h... yes
checking for library containing regfree... none required
checking for compatible POSIX regex... yes
checking sys/uuid.h usability... no
checking sys/uuid.h presence... no
checking for sys/uuid.h... no
checking uuid/uuid.h usability... no
checking uuid/uuid.h presence... no
checking for uuid/uuid.h... no
checking to see if -lrpcrt4 is needed for win32 UUID support... no
checking for resolver link (default)... no
checking for resolver link (-lresolv)... yes
checking for hstrerror... yes
checking for getaddrinfo... yes
checking for getnameinfo... yes
checking for gai_strerror... yes
checking for inet_ntop... yes
checking INET6_ADDRSTRLEN... yes
checking struct sockaddr_storage... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for SSL_CTX_set_msg_callback in -lssl... yes
checking OpenSSL library version (CRL checking capability)... yes
checking for _beginthread... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking POSIX thread version... 10
checking for LinuxThreads pthread.h... no
checking for GNU Pth pthread.h... no
checking sched.h usability... yes
checking sched.h presence... yes
checking for sched.h... yes
checking for pthread_create in default libraries... no
checking for pthread link with -kthread... no
checking for pthread link with -pthread... yes
checking for sched_yield... yes
checking for pthread_yield... yes
checking for thr_yield... no
checking for pthread_kill... yes
checking for pthread_rwlock_destroy with <pthread.h>... yes
checking for pthread_detach with <pthread.h>... yes
checking for pthread_setconcurrency... yes
checking for pthread_getconcurrency... yes
checking for thr_setconcurrency... no
checking for thr_getconcurrency... no
checking for pthread_kill_other_threads_np... no
checking for LinuxThreads implementation... no
checking for LinuxThreads consistency... no
checking if pthread_create() works... yes
checking if select yields when using pthreads... yes
checking for thread specific errno... yes
checking for thread specific h_errno... yes
checking for ctime_r... yes
checking for gmtime_r... yes
checking for localtime_r... yes
checking for gethostbyname_r... yes
checking for gethostbyaddr_r... yes
checking number of arguments of ctime_r... 2
checking number of arguments of gethostbyname_r... 6
checking number of arguments of gethostbyaddr_r... 8
checking db.h usability... no
checking db.h presence... no
checking for db.h... no
configure: error: BDB/HDB: BerkeleyDB not available
```
